spring:
  application:
    name: ipl-assignment

  datasource:
    url: jdbc:mysql://localhost:3306/ipl
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    serialization:
      indent_output: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      port: 6379
  cache:
    redis:
      time-to-live: 600000
      key-prefix: "ipl:"
      use-key-prefix: true
      enable-statistics: true
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security-protocol: PLAINTEXT
      SASL_MECHANISM: PLAIN
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 5000



